/tmp/ccoH4FbT.o: En la funci√≥n `themainmainfunction':
shield_c.c:(.text+0x16): referencia a `errorNo1' sin definir
collect2: error: ld returned 1 exit status
